<a href="https://colab.research.google.com/github/RhinoBlindado/vc2122/blob/main/p1_introToOpenCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Práctica 0**: Introducción a OpenCV
ayyy

---
## **Preámbulo**
### Añadiendo librerías
---

In [25]:
#   Give Google Colab Access to Google Drive
from google.colab import drive
drive.mount("/content/drive/")

#   Using Matplotlib to show images
import matplotlib.pyplot as plt
import matplotlib.colors as clr

#   Using OpenCV for everything else related to images.
import cv2 as cv

#   Using Numpy to manipulate images
import numpy as np

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


---
##**Ejercicio 1** 


### Escribir una función que lea el fichero de una imagen y permita mostrarla tanto en grises como en color

---


In [26]:
def leeImagen(filename, flagColor):
    """
    Read an image from file.
    
    Parameters
    ----------
    filename : String
        Path to a valid image file.
    flagColor : Boolean
        Value indicating to read the image with RGB (True) or Grayscale (False).

    Returns
    -------
    TYPE
        DESCRIPTION.

    """
    return cv.imread(filename, int(flagColor))

In [35]:


#   Path the test images.
srcOrapple = "/content/drive//MyDrive/Colab Notebooks/images/orapple.jpg"
srcMessi = "/content/drive//MyDrive/Colab Notebooks/images/messi.jpg"
srcLogo = "/content/drive//MyDrive/Colab Notebooks/images/logoOpenCV.jpg"
srcDave = "/content/drive//MyDrive/Colab Notebooks/images/dave.jpg"

#   Reading image as greyscale.
imageOrappleGrey = leeImagen(srcOrapple, False)
#   Now with colors.
imageOrappleColor = leeImagen(srcOrapple, True)

#   Rest of images
imageDave = leeImagen(srcDave, False)
imageMessi = leeImagen(srcMessi, False)
imageLogo = leeImagen(srcLogo, True)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [196 196 196]
  [196 196 196]
  [196 196 196]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [107 107 107]
  [107 107 107]
  [107 107 107]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[252 252 252]
  [252 252 252]
  [252 252 252]
  ...
  [204 204 204]
  [248 248 248]
  [248 248 248]]

 [[254 254 254]
  [254 254 254]
  [254 254 254]
  ...
  [246 246 246]
  [252 252 252]
  [252 252 252]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
